### ISSUE TITLE
Not implemented but took name on rubygems

### ISSUE THREAD

**Issue by FreedomBen** [blacktm/tello#1]
It's a little disappointing that you are squatting on the name `tello` on rubygems with an empty gem.  A week or two might be fine, but it's pretty bad form to do this for several months.

When do you intend to finish your implementation?

**Comment by blacktm** [comment]
Glad to see there's interest in the gem. 😉 Apparently GitHub doesn't auto-watch repos you create, so I never got a notification for this issue, hence not seeing/replying to it. I did get copied via email on the issue submitted to RubyGems.org. The intent was not to squat on the name (not sure of the value in doing that). I had plans for some initial functionality to release, but in addition to family and work taking priority, interacting with the hardware turned out to be a bit more complicated than anticipated. There are still some bugs to work through, but I've at least pushed the initial implementation to a public PR (at #2) so the development is transparent. While I don't know when I'll publish this first attempt in a new version of the gem, it's getting more stable each day, so should be soon.

**Comment by blacktm** [comment]
[New version](https://rubygems.org/gems/tello/versions/0.1.0) of the gem just published with initial functionality, enjoy!

**Comment by FreedomBen** [comment]
Oh dude!  I am "watching" this repo and I still didn't get notified of the activity :-(  

This is starting to look really good man, thanks!  I also totally understand family and work taking priority (they definitely should, and they do for me as well).  I'll give the first version a try and send any feedback/PRs that I run into :-)

**Comment by blacktm** [comment]
Thanks. Did you get a chance to try it out?

**Comment by FreedomBen** [comment]
Sadly no, my tello has been decommissioned due to an accident (dang kids :-) ), but Santa is expected to bring one to my house in a week, so I'm hoping to have some fun with it on Christmas break
